#!/usr/bin/env ruby
# frozen_string_literal: true

require "mcp_compose"

server_builder = MCPCompose::ServerBuilder.new
config_parser = MCPCompose::ConfigParser.new(cwd: Dir.pwd)
cli = MCPCompose::CLI.new(server_builder: server_builder, config_parser: config_parser)

begin
  cli.run
rescue MCPCompose::CLI::Error => e
  warn e.message
  exit 1
end
