#!/usr/bin/env ruby
# frozen_string_literal: true

require "mcp_compose"

config_parser = MCPCompose::ConfigParser.new(cwd: Dir.pwd)
parse_config = ->(content) { config_parser.parse(content) }

build_server = ->(config) do
  MCPCompose::Server.new(config: config)
end

cli = MCPCompose::CLI.new(parse_config_function: parse_config, build_server_function: build_server)
shell_context = MCPCompose::Util::ShellContext.new(cwd: Dir.pwd)

begin
  cli.run(shell_context: shell_context)
rescue MCPCompose::CLI::Error => e
  warn e.message
  exit 1
end
