#!/usr/bin/env ruby
# frozen_string_literal: true

require "mcp_compose"

run_server = ->(config) do
  MCPCompose::Server.new(config: config).run
end

cli = MCPCompose::CLI.new(run_server_function: run_server, config_parser: MCPCompose::ConfigParser.new)

begin
  cli.run
rescue MCPCompose::CLI::Error => e
  warn e.message
  exit 1
end
